### ISSUE TITLE
Research Callbacks Vs. Promises

### ISSUE THREAD

**Issue by estefaniaguardado** [EstefaniaGuardado/weightApp#32]
References:

- [Managing async Code in Swift](https://medium.com/ios-os-x-development/managing-async-code-in-swift-d7be44cae89f)
- [Promise Pattern on Swift with PromiseKit](https://hackernoon.com/promise-pattern-on-swift-with-promisekit-620efad7a5bd)

Framework:
- [PromiseKit](https://github.com/mxcl/PromiseKit)

Conclusion:
This issue born when existing functions or cases that need an asynchronous response and the result of the first one is the input of the next one to continue the process.

The inclusion of callbacks in this particular situation it would be making "Callback hell" (painful and difficult to maintain it), and regarding with the research, it's the implementation of Promises an enhancement in many ways (clean code, maintainability, etc)

**Comment by EstefaniaGuardado** [comment]
References:

- [Managing async Code in Swift](https://medium.com/ios-os-x-development/managing-async-code-in-swift-d7be44cae89f)
- [Promise Pattern on Swift with PromiseKit](https://hackernoon.com/promise-pattern-on-swift-with-promisekit-620efad7a5bd)

Framework:
- [PromiseKit](https://github.com/mxcl/PromiseKit)
